name: Update crypto price CSV

on:
  schedule:
    - cron: '0 0 * * *'   # Every 24 hours (UTC)
  workflow_dispatch:          # Also allow manual trigger

jobs:
  update_csv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt || true

    - name: Run tracker script
      run: |
        python crypto_price_scraper.py

    - name: Commit and push if CSV changed
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add crypto_prices.csv
        git diff --cached --quiet || (git commit -m "Update crypto_prices.csv [skip ci]" && git push)
